version: '3.4'

services:
  naive:
    image: jiasongji/naiveproxy-docker
    container_name: naiveproxy
    tty: true
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data:/data
      - ./share:/root/.local/share
<certVolumes>
    command: ["/bin/bash", "/data/entry.sh"]
