version: '3.4'

services:
  naive:
    image: zai7lou/naiveproxy-docker
    container_name: naiveproxy
    tty: true
    restart: unless-stopped
    # 以下是旧的网络配置，改为使用宿主网络模式
    # ports:
    #   - <httpPort>:<httpPort>
    #   - <httpsPort>:<httpsPort>
    network_mode: "host"
    volumes:
      - ./data:/data
      - ./share:/root/.local/share
      <certVolumes>
      <certKeyVolumes>
    command: ["/bin/bash", "/data/entry.sh"]
